#! /bin/sh

stabilize ()
{
    sed "s,$PWD,€PWD," | sed -r 's,[0-9]+\.[0-9]+,x,g' |
        sed -r 's,/tmp/scratch-unit-test-kak\.[^/]*,€SCRATCH_UNIT_TEST_DIR,g'
}

s=bin/scratch-unit-test-kak
"$s" | stabilize >"$s.out" 2>"$s.err"
