#! /bin/bash

window_name=screenshot

if ! test "$TMUX"; then
    echo "${0##*/}: error: this script must be ran within a tmux session"
    exit 1
fi >&2

if test $# -ne 2; then
    echo "usage: ${0##*/} <spec_file> <output_file>"
    exit 1
fi >&2

spec_file="$1"
output_file="$2"

tmux kill-window -t "$window_name" 2>/dev/null

clean_up () {
    code=$?
    tmux kill-window -t "$window_name"
    exit $code
}

trap clean_up EXIT

tmux_and_sleep ()
{
    tmux "$@"
    sleep 0.5
}

tmux_and_sleep new-window -n "$window_name"
tmux_and_sleep split-window -h -d
tmux_and_sleep send-keys -t "$window_name".1 "kak '$spec_file'" Enter
tmux_and_sleep send-keys -t "$window_name".2 'env PATH="$PWD/bin:$PATH" sh' Enter
tmux_and_sleep send-keys -t "$window_name".2 'clear' Enter
tmux_and_sleep send-keys -t "$window_name".2 "kak-spec '$spec_file'" Enter
tmux_and_sleep run-shell "gnome-screenshot -w --file='$output_file'"
tmux_and_sleep send-keys -t "$window_name".1 ':q' Enter

# Scale the output file down.
convert "$output_file" -scale 50% "$output_file.png"
mv "$output_file.png" "$output_file"
